name: Build and Sign Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PATH: app/my-release-key.jks  # 统一密钥库路径变量
    steps:
      # 步骤 1：拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2：设置 JDK 环境
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 步骤 3：解码并写入密钥库文件
      - name: Setup Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $KEYSTORE_PATH
          ls -l $KEYSTORE_PATH  # 验证文件存在

      # 步骤 4：赋予 Gradle 执行权限
      - name: Grant Gradle Permission
        run: chmod +x gradlew

      # 步骤 5：构建 Release APK（传递签名环境变量）
      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 步骤 6：验证 APK 路径
      - name: Verify APK Path
        run: |
          ls -R app/build/outputs/apk/release/
          [ -f app/build/outputs/apk/release/*.apk ] || exit 1

      # 步骤 7：上传 APK 产物
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
